//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.TestApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Company.TestApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories structure are same.
        /// </summary>
        public static string DirectoriesstructureAreSame {
            get {
                return ResourceManager.GetString("DirectoriesstructureAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} directory doesn&apos;t exists.
        /// </summary>
        public static string DirectoryDoesNotExists {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} directory exception: {1}.
        /// </summary>
        public static string DirectoryException {
            get {
                return ResourceManager.GetString("DirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} directory without value.
        /// </summary>
        public static string DirectoryWithoutValue {
            get {
                return ResourceManager.GetString("DirectoryWithoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details :  {0}.
        /// </summary>
        public static string ErrorDetailDetails {
            get {
                return ResourceManager.GetString("ErrorDetailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class DirectoryStructure is null.
        /// </summary>
        public static string TheClassDirectoryStructureIsNull {
            get {
                return ResourceManager.GetString("TheClassDirectoryStructureIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first.
        /// </summary>
        public static string TheFirst {
            get {
                return ResourceManager.GetString("TheFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second.
        /// </summary>
        public static string TheSecond {
            get {
                return ResourceManager.GetString("TheSecond", resourceCulture);
            }
        }
    }
}
